[#32] Diagrama de componentes
UnBArqDsw2020-2/2020.2_G2_Encare pull request #38
Opened 2021-03-03 03:05 UTC by Gustavo-Nogueira

## Descrição

- Adiciona a página de diagrama de componentes contendo duas versões do artefato.

2021-03-06 17:44 UTC, nicaloribeiro commented
A princípio está tudo ok.

2021-03-06 17:46 UTC, nicaloribeiro approved these changes

2021-03-08 03:06 UTC, jps12 requested changes
![image](https://user-images.githubusercontent.com/50410689/110268991-7982a780-7fa1-11eb-89c9-423a997a12dd.png)

Acho que o diagrama tem que ser sobre o MVP, e nesse caso esse módulo não existe dentro do MVP.

Outro ponto é que esse diagrama tem divergências em relação ao diagrama de sequências, pois no de sequência o filtro é algo que depende do backend e nesse de componente ao que parece não depende, posso estar enganado.

2021-03-08 04:39 UTC, Gustavo-Nogueira commented
@jps12 

Beleza !  @wagnermc506, podemos remover o InstagramScrapper  ?

Quanto ao componente "Filter", toda parte de request e armazenamento do front-end será/poderá feita por meio do componente **genérico** "Store", dessa forma, o componente "Store" que será responsável pela parte de comunicação com o back-end. Isso é bem alto nível, mas a ideia é separar a lógica de requests da lógica do componente em si, assim podendo reaproveitar melhor os componentes, estrutura de requests etc. Vou tentar documentar melhor essa parte.

2021-03-08 12:48 UTC, wagnermc506 commented
@Gustavo-Nogueira Podemos remover sim. 

@jps12 
Quanto a questão do filtro. O que está a ser mostrado no front-end seria a tela ou componente que mostra as seleções de filtragem, onde o usuário pode interagir. A lógica para realizar a filtragem em si seria feita pela controller no back-end. Este filtro pode estar em um query que já aplica as operações pra obter apenas os estabelecimentos/imagens desejados ou poderia ser feito com alguma lógica depois da query.

2021-03-08 15:16 UTC, jps12 approved these changes
Entendi os pontos de vista esclarecidos. Tudo está de acordo. Falta apenas a revisão do @RenatoBrittoAraujo

2021-03-08 15:23 UTC, RenatoBrittoAraujo approved these changes

2021-03-08 15:24 UTC, merged