[#36] Protótipo alta fidelidade
UnBArqDsw2020-2/2020.2_G2_Encare pull request #61
Opened 2021-03-19 02:40 UTC by nicaloribeiro

- Primeira versão da página com os protótipos de média e alta fidelidade.

2021-03-19 13:11 UTC, wagnermc506 approved these changes
Arquivos revisados. Sem erros encontrados

2021-03-19 13:39 UTC, jps12 requested changes
Só relacionado ao iframe quebrado e o doc de protótipo tem que estar na página de Iniciativas extras.

2021-03-19 13:39 UTC, jps12 commented on docs/Padroes/prototipos/prototipo_alta.md
> +<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FxJ49RxNyO7ulXwd86Gxbov%2FUnt
Pelo menos aqui o iframe esta quebrado, no gh-pages deu certo?

2021-03-19 15:13 UTC, Gustavo-Nogueira commented on docs/Padroes/prototipos/prototipo_alta.md
> +<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FxJ49RxNyO7ulXwd86Gxbov%2FUnt
@jps12 sim, funcionou perfeitamente.

2021-03-19 17:12 UTC, jps12 approved these changes

2021-03-23 23:19 UTC, RenatoBrittoAraujo approved these changes

2021-04-10 00:11 UTC, Gustavo-Nogueira approved these changes
Aprovado !

2021-04-10 00:12 UTC, merged